### ISSUE TITLE
ERROR Could not pass event ChunkPopulateEvent to MagicLoot v2.1.0

### ISSUE THREAD

**Issue by SpiritAmet** [TheBusyBiscuit/MagicLoot3#4]
We seem to be getting this issue alot in our console.

We are using Spigot 1.12.2

![2017-12-15_23 30 27](https://user-images.githubusercontent.com/30029036/34075222-c8f883de-e274-11e7-9aaf-3508be8fd5e1.png)
This is the rest of the version info.

https://pastebin.com/iPTgP80d is the full logs of the issue.

**Comment by extral1f3** [comment]
Lets get some more info on this please. I am having the same issue.
